### ISSUE TITLE
projmake-mode no longer works on melpa.

### ISSUE THREAD

**Issue by milkypostman** [ericbmerritt/projmake-mode#12]
https://github.com/ericbmerritt/projmake-mode/commit/9aef43bbc9c716751bea363dc274e0744af6d7c9#diff-c2acf6b092a79ea5ac1c0d6e9ee3081c

This commit is causing problems because `indicators` doesn't have a version number.

**Comment by ericbmerritt** [comment]
@milkypostman this should work now. There where a couple of issues, but they should be resolved. Would you confirm for me?
