### ISSUE TITLE
Configurable automatic split display of error list buffer

### ISSUE THREAD

**Issue by tsloughter** [ericbmerritt/projmake-mode#9]
It would be great to be able to turn off the automatic split of the window to display the error list buffer everytime projmake runs. Even better would be to be able to turn it off and easily set a keybinding which does the split and opening of the error list buffer in the new window.

**Comment by tsloughter** [comment]
@ericbmerritt any thoughts? I think I fixed it but forget, hehe. I'm going to go back to trying to get projmake working for me well again soon.

**Comment by ericbmerritt** [comment]
Hmm. you can turn it off (and maybe it should be off by default). There are two variables that control this: `projmake-show-error-list-buffer` which is `t` by defualt and `projmake-show-build-output-buffer` which is `nil` by default. You can setq one or both of these to nil and it will turn off the 'auto pop up` behavior. @wardbekker sorry for the delay here. Its only recently that I got things setup so I actually see my github notifications.

**Comment by ericbmerritt** [comment]
btw. I am super open to changing this. I have found the auto-pop up a bit annoying of late as well.

**Comment by wardbekker** [comment]
(setq projmake-show-error-list-buffer nil) is OK if I can disable the  auto hiding/closing of the error-list-buffer? That combination would work for me.

**Comment by ericbmerritt** [comment]
@wardbekker That should disable that behaviour. Would you verify that for me?

**Comment by wardbekker** [comment]
@ericbmerritt I've tested it with the projmake-mode version that's on melpa (20140909.729) with (setq projmake-show-error-list-buffer nil). It does not auto-show the error-list-buffer (preferred), but it does try to delete the error-list buffer after a successful compile (not preferred). If no error-list buffer is open, it tries to delete the minibuffer, which results in the following message: "error in process sentinel: Attempt to delete minibuffer or sole ordinary window". Let me know if you need more info.

**Comment by ericbmerritt** [comment]
@wardbekker thanks. I will get that fixed and push it. I will update this here when I push the changes.

**Comment by ericbmerritt** [comment]
@wardbekker I can't net replicate this. at least with current master.

**Comment by ericbmerritt** [comment]
btw, I am about to make not showing the error buffer default. So I would love it if you all ( @wardbekker  & @tsloughter) could try out my current master.

**Comment by wardbekker** [comment]
Cool. Going to test it. Thx!

**Comment by wardbekker** [comment]
Behavior as described in https://github.com/ericbmerritt/projmake-mode/issues/9#issuecomment-73508953 is still present for me in current master. I use Emacs Version 24.5 (9.0)

**Comment by ericbmerritt** [comment]
@wardbekker I will try continue to try to fix this. I think I just noticed what I was missing.

**Comment by ericbmerritt** [comment]
@wardbekker one more try please.

**Comment by wardbekker** [comment]
@ericbmerritt ok, will check today. Thx!
